- .github/workflows/sync-github.yml
> remove action concurrency

- .gitignore
- examples/test_utils.py
- setup.py
- src/dflow/utils.py
1. Update `.gitignore` and `setup.py`
2. Add `set_directory` and `run_command` in utils
> Add common util functions

- README.md
- src/dflow/step.py
> add docs for with_param and with_sequence

- examples/test_utils.py
> fix FileNotFoundError in test_utils.py

- src/dflow/utils.py
> fix a bug in copy_artifact when sort=True and dst artifact is empty

- .github/workflows/ci-pypi.yml
- docs/developer.md
- scripts/install-linux.sh
- scripts/install-mac.sh
- src/dflow/io.py
- src/dflow/utils.py
> feat: add server-side installation script for Linux feat: add developer guide feat: make ArgoVar uniterable fix: fix a bug of path on Windows

- src/dflow/io.py
> fix(IfExpression): transfer to right string.

- .github/workflows/ci-docker.yml
> fix: github action of building docker image fails

- src/dflow/dag.py
- src/dflow/op_template.py
- src/dflow/steps.py
- src/dflow/workflow.py
> fix: bugs of reuse

- scripts/install-linux-cn.sh
- scripts/install-mac-cn.sh
- tutorials/install_manual_linuxos.md
- tutorials/install_manual_macos.md
- tutorials/install_manual_windowsos.md
- tutorials/readme.md
- add installation script for users in China
- update installation guide different OS
> baby step installation guide

- src/dflow/op_template.py
- src/dflow/python/python_op_template.py
- src/dflow/workflow.py
fix: add workflow actions: terminate, delete, resubmit, resume, retry, stop, suspend
> fix: add envs to script op template fix: add workflow actions: terminate, delete, resubmit, resume, retry, stop, suspend

- src/dflow/config.py
- src/dflow/executor.py
- src/dflow/plugins/dispatcher.py
- src/dflow/slurm.py
- src/dflow/step.py
- src/dflow/task.py
- src/dflow/util_ops.py
> fix: add image_pull_policy for util images

- src/dflow/python/op.py
skip optional artifact signature check.
> skip optional artifact

- src/dflow/executor.py
- src/dflow/slurm.py
> fix: mkdir return 0 and upload failed

- manifests/quick-start-postgres.yaml
> fix: update latest yaml

- examples/test_ray.py
- examples/test_ray_after_ray.py
- src/dflow/op_template.py
- src/dflow/plugins/ray.py
- src/dflow/python/python_op_template.py
These commits add features of Ray executor support custom dependencies, as https://docs.ray.io/en/latest/ray-core/handling-dependencies.html using `py_modules`, saying in #34.
And Ray executor needs `init_container` to check and establish environment.
> feat(Ray Executor): Ray executor with dependencies settings.

- src/dflow/workflow.py
> fix: add pod GC strategy

- src/dflow/python/python_op_template.py
> fix: add method render_script to PythonOPTemplate

- src/dflow/plugins/dispatcher.py
> fix: skip uploading non-existing files in dispatcher executor

- src/dflow/io.py
> fix: __getitem__ of ArgoVar handle non-string items

- src/dflow/step.py
> fix: a bug of handling multiple big parameters

- src/dflow/io.py
> fix: pass save_as_aritfact for value_from_expression

- src/dflow/python/python_op_template.py
- src/dflow/python/utils.py
> fix: restore availability of download_sliced_output_artifact

- src/dflow/__init__.py
fix: S3Artifact exported twice in __init__.py.
> fix: remove duplicate export class: S3Artifact

- src/dflow/plugins/lebesgue.py
> fix: mixed mode for lebesgue executor

- src/dflow/io.py
- src/dflow/python/python_op_template.py
- src/dflow/step.py
- src/dflow/task.py
> fix: add parallelism for sliced step

- src/dflow/executor.py
- src/dflow/plugins/dispatcher.py
- src/dflow/slurm.py
> fix: support for any private key file name

- src/dflow/step.py
> fix: support parallelism for a parallel step other than sliced step

- src/dflow/dag.py
- src/dflow/step.py
- src/dflow/steps.py
fix: pass steps/tasks in the initialization of Steps/DAG
> fix: prepare_step is None fix: pass steps/tasks in the initialization of Steps/DAG

- examples/test_dispatcher.py
- examples/test_slurm.py
- scripts/docker-compose.yml
- scripts/register_cluster.sh
- scripts/start-slurm.sh
> fix: add slurm docker cluster for autotests

- src/dflow/plugins/dispatcher.py
- src/dflow/python/op.py
- src/dflow/python/python_op_template.py
- src/dflow/utils.py
> fix: add methods for OP to get s3 key/link of input/output artifacts

- src/dflow/utils.py
- src/dflow/workflow.py
fix: add image pull secrets for workflow
> fix: support for skipping same files while downloading fix: add image pull secrets for workflow

- src/dflow/workflow.py
> fix: save uid after submission

- requirements.txt
- setup.py
- src/dflow/plugins/lebesgue.py
> fix: add requests to dependencies

- src/dflow/step.py
> fix: bug of parallelism for sliced step with sequence

- src/dflow/workflow.py
fix: print uid when submitting
> fix: add reused keys to global outputs

- src/dflow/plugins/dispatcher.py
- src/dflow/step.py
- src/dflow/util_ops.py
fix: pass n_total explicitly in continue_on_success_ratio
> fix: omit queue_name if it is None in dispatcher executor fix: pass n_total explicitly in continue_on_success_ratio

- src/dflow/python/python_op_template.py
> fix: add pool_size for slices

- src/dflow/python/python_op_template.py
> fix: a typo

- src/dflow/step.py
fix: optional input artifact in debug mode
> fix: use subprocess.Popen in debug mode

- src/dflow/step.py
- src/dflow/utils.py
> fix: support for python3.7 in debug mode

- README.md
> fix: add readme for debug mode

- README.md
- src/dflow/python/op.py
- src/dflow/step.py
> fix: slice by group in debug mode fix: enhance error message fix: port-forward --address 0.0.0.0 in readme

- src/dflow/step.py
- src/dflow/workflow.py
> fix: slices for Steps/DAG fix: add artifact_repo_key

- src/dflow/__init__.py
- src/dflow/argo_objects.py
- src/dflow/common.py
- src/dflow/config.py
- src/dflow/io.py
- src/dflow/plugins/bohrium.py
- src/dflow/python/op.py
- src/dflow/python/python_op_template.py
- src/dflow/step.py
- src/dflow/utils.py
- src/dflow/workflow.py
fix: add bohrium storage client
> fix: support for storage plugins fix: add bohrium storage client

- src/dflow/config.py
- src/dflow/io.py
- src/dflow/op_template.py
- src/dflow/workflow.py
> fix: parse repo info from configmap

- src/dflow/step.py
> fix: future len of input parameter

- src/dflow/workflow.py
> fix: get k8s client when used

- src/dflow/utils.py
> fix: download S3Artifact

- src/dflow/common.py
- src/dflow/plugins/bohrium.py
> fix: add to_dict and from_dict methods to S3Artifact

- src/dflow/common.py
> fix: add download method to S3Artifact

- src/dflow/plugins/bohrium.py
- src/dflow/step.py
> fix: bug in collecting output parameters of sliced step fix: support for setting bohrium url for bohrium executor

- src/dflow/__init__.py
- src/dflow/step.py
- src/dflow/util_ops.py
> fix: add argo_sum and argo_concat

- src/dflow/python/opio.py
- src/dflow/python/utils.py
- src/dflow/workflow.py
> fix: support for always passing root path of artifact

- src/dflow/common.py
- src/dflow/step.py
- src/dflow/util_ops.py
> fix: no prefix when user use S3Artifact()

- src/dflow/plugins/lebesgue.py
- src/dflow/python/op.py
- src/dflow/python/python_op_template.py
fix: add host addr for lebesgue executor
> fix: make OP function callable

- src/dflow/plugins/dispatcher.py
> fix: bohrium in dispatcher executor

- src/dflow/executor.py
- src/dflow/plugins/bohrium.py
- src/dflow/plugins/dispatcher.py
- src/dflow/plugins/lebesgue.py
- src/dflow/slurm.py
> fix: use render_script method to map /tmp to $(pwd)/tmp for PythonOPTemplate

- scripts/install-linux-cn.sh
- scripts/install-mac-cn.sh
- src/dflow/common.py
- src/dflow/config.py
- src/dflow/plugins/bohrium.py
> fix: replace github link with gitee link in install-*.sh fix: add extra prefixes ignored by S3Artifact auto-prefixing

- src/dflow/python/python_op_template.py
- src/dflow/python/utils.py
- src/dflow/step.py
> fix: support for pass list of artifacts to input artifact

- examples/test_lineage.py
- src/dflow/__init__.py
- src/dflow/common.py
- src/dflow/config.py
- src/dflow/io.py
- src/dflow/plugins/metadata.py
- src/dflow/python/python_op_template.py
- src/dflow/python/utils.py
- src/dflow/step.py
- src/dflow/utils.py
- src/dflow/workflow.py
> add lineage and metadata client

- src/dflow/op_template.py
> fix: support for env from a source

- src/dflow/__init__.py
- src/dflow/op_template.py
- src/dflow/workflow.py
> fix: create secret for env var

- src/dflow/workflow.py
> add http headers when creating configmap

- src/dflow/__init__.py
- src/dflow/config.py
- src/dflow/plugins/bohrium.py
> fix: support for config from env var

- src/dflow/plugins/bohrium.py
- src/dflow/plugins/dispatcher.py
- src/dflow/plugins/lebesgue.py
- src/dflow/step.py
- src/dflow/workflow.py
fix: executor used for context
> fix: dispatcher bohrium use bohrium.config

- src/dflow/plugins/dispatcher.py
> fix: output parameter has no attribute path

- src/dflow/plugins/bohrium.py
- src/dflow/plugins/lebesgue.py
- src/dflow/steps.py
> fix: refresh token in tiefblue client fix: remove empty step group

- src/dflow/argo_objects.py
> fix: enhance query_step efficiency

- src/dflow/argo_objects.py
> fix: ArgoStep not idempotent

- src/dflow/argo_objects.py
> fix: ArgoStep deepcopy input dict

- src/dflow/step.py
> fix: unclosed file ResourceWarning

- src/dflow/plugins/bohrium.py
> fix: no share path for non-dp user

- src/dflow/argo_objects.py
- src/dflow/plugins/dispatcher.py
- src/dflow/step.py
- src/dflow/workflow.py
> fix: enhance performance of querying and reusing fix: duplicate template name when multiple continue_on_success_ratio used

- src/dflow/step.py
> fix: continue_on_success_ratio used with executor

- src/dflow/plugins/dispatcher.py
> fix: add log to Bohrium dispatcher executor fix: add retry to dispatcher executor

- src/dflow/utils.py
> fix: add try_bash to run_command

- src/dflow/step.py
> fix: continue on number/ratio skip errors

- src/dflow/utils.py
> fix: use bash -ic instead of bash -lc

- src/dflow/plugins/dispatcher.py
- src/dflow/step.py
- src/dflow/utils.py
fix: sys.stdin.encoding -> sys.stdout.encoding
> fix: workaround for unavailable exit code of Bohrium job;

- src/dflow/utils.py
> fix: add argument interactive to run_command

- src/dflow/argo_objects.py
- src/dflow/plugins/oss.py
- src/dflow/python/op.py
- src/dflow/python/opio.py
- src/dflow/python/utils.py
- src/dflow/utils.py
> fix: support dict of path for artifact fix: add oss storage client fix: add warns for handling argo objects

- src/dflow/python/python_op_template.py
- src/dflow/step.py
> fix: add group_size feature for slices

- src/dflow/io.py
> fix: set default mode to 755 for input artifacts

- src/dflow/io.py
> fix: set default mode to None for input artifacts

- requirements.txt
- setup.py
- src/dflow/config.py
- src/dflow/workflow.py
> fix: add workflow_annotations to global config fix: restrict jsonpickle==2.2.0

- src/dflow/step.py
> fix: support group_size for debug mode

- src/dflow/op_template.py
- src/dflow/python/opio.py
- src/dflow/python/python_op_template.py
- src/dflow/workflow.py
> fix: save key2id map in global outputs, add query_step_by_key fix: support default value of big parameter

- src/dflow/workflow.py
> fix: downgrade for query_step_by_key

- src/dflow/io.py
- src/dflow/workflow.py
> fix: add API query_global_outputs fix: prepend dflow_bigpar_ to global name of parameter saved as artifact

- src/dflow/io.py
> fix: let argument override default value of big parameter

- src/dflow/plugins/oss.py
- src/dflow/workflow.py
> fix: different behaviors of OSS client fix: add comments to query functions

- src/dflow/plugins/dispatcher.py
> fix: fix dispatcher bohrium cannot sync log

- src/dflow/op_template.py
> fix: save key-id mapping for super OP

- src/dflow/python/python_op_template.py
- src/dflow/workflow.py
> fix: jsonpickle.loads failed in bohrium executor

- src/dflow/plugins/bohrium.py
- src/dflow/python/utils.py
> fix: add API for creating bohrium job group ID fix: support for slicing big parameter

- src/dflow/argo_objects.py
- src/dflow/io.py
- src/dflow/python/utils.py
- src/dflow/step.py
> fix: direct jsonpickle.dumps for big parameter fix: support for argo_len of big parameter

- src/dflow/dag.py
- src/dflow/op_template.py
- src/dflow/step.py
- src/dflow/steps.py
- src/dflow/workflow.py
fix: deduplicate argo templates
> fix: shallow copy super op

- src/dflow/plugins/dispatcher.py
fix: make dispatcher executor consistent in debug mode and default mode
fix: remove workaround for unavailable exit code of Bohrium job
fix: retry on network error in dispatcher executor
> fix: kill jobs on sigterm in dispatcher executor

- requirements.txt
- setup.py
- src/dflow/executor.py
> fix: copy singularity instead of symlink

- src/dflow/common.py
- src/dflow/config.py
- src/dflow/io.py
- src/dflow/step.py
- src/dflow/utils.py
fix: upload_s3 in debug mode
fix: reconstruct download artifact in debug mode
fix: bug in optional artifact in debug mode
> fix: add debug_artifact_dir

- src/dflow/dag.py
- src/dflow/step.py
- src/dflow/steps.py
- src/dflow/utils.py
- src/dflow/workflow.py
fix: add option id when querying archived workflows
> fix: stuck when exiting ProcessPoolExecutor

- src/dflow/step.py
fix: debug: optional output artifact
fix: debug: wait for the download to complete
> fix: debug: optional artifact from output artifact

- src/dflow/python/python_op_template.py
- src/dflow/step.py
fix: unpicklable function OP in debug mode
> fix: handle sub_path slices of artifact list for debug mode

- src/dflow/python/opio.py
- src/dflow/python/utils.py
> fix: HDF5Datasets with grouped slices

- requirements.txt
- setup.py
- src/dflow/dag.py
- src/dflow/step.py
- src/dflow/steps.py
- src/dflow/workflow.py
fix: support restart of any workflow in debug mode
> fix: save children structure in debug mode

- manifests/quick-start-postgres-3.4.1-deepmodeling.yaml
- src/dflow/argo_objects.py
fix: no secret of service account for new versions of k8s
> fix: 'ValuesView' object has no attribute 'sort'
